# -*- coding: utf-8 -*-
"""AyushiPatani

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11f6y1BOiIx07RcZiQoyeK3fwx80XUOxH

**Python web scraping**
"""

from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd
import matplotlib.pyplot as plt

csv_file = open('college_details.csv','w', newline='')
csv_writer = csv.writer(csv_file)
csv_writer.writerow(['Institute Code', 'College Name', 'Region', 'Region Type', 'College Address', 'Email Address', 'Website', 'Registrar Name', 'Principal Name','Office Phone', 'Fax No', 'Status','Autonomy Status', 'Minority status'])
for i in range (1002, 6961): #using institute ocde to get the url
  s = "http://dtemaharashtra.gov.in/frmInstituteSummary.aspx?InstituteCode="+str(i)
  try:
      r = requests.get(s).text
      soup = BeautifulSoup(r, 'lxml')
  except Exception as e:  #try catch block to handle if page not found
      continue
  check = 0
  for table in soup.findAll( "table", attrs={"class": "AppFormTableNew"}): 
      field = table.tr.th.text
      if(field.find("Engineering") != -1):
          check = 1
          break
  if(check != 1):
      continue
  soup.find(id='').text
  #fetching all the required data by id
  insti_code = i
  name = soup.find(id='ctl00_ContentPlaceHolder1_lblInstituteNameEnglish').text
  region = soup.find(id='ctl00_ContentPlaceHolder1_lblRegion').text
  region_type = soup.find(id='ctl00_ContentPlaceHolder1_lblRegionType').text
  address = soup.find(id='ctl00_ContentPlaceHolder1_lblAddressEnglish').text
  email_add = soup.find(id='ctl00_ContentPlaceHolder1_lblEMailAddress').text
  website = soup.find(id='ctl00_ContentPlaceHolder1_lblWebAddress').text
  registrar = soup.find(id='ctl00_ContentPlaceHolder1_lblRegistrarNameEnglish').text
  principal = soup.find(id='ctl00_ContentPlaceHolder1_lblPrincipalNameEnglish').text
  contact = soup.find(id='ctl00_ContentPlaceHolder1_lblOfficePhoneNo').text.split(" ")
  contact_no = contact[0]
  fax = soup.find(id='ctl00_ContentPlaceHolder1_lblFaxNo').text.split(" ")[0]
  status = soup.find(id='ctl00_ContentPlaceHolder1_lblStatus1').text
  autonomy = soup.find(id='ctl00_ContentPlaceHolder1_lblStatus2').text
  minority = soup.find(id='ctl00_ContentPlaceHolder1_lblStatus3').text

  if(name == '' or website == '' or contact_no == '' or email_add ==''):
      continue
  print(name)
  csv_writer.writerow([insti_code,name,region,region_type,address,email_add, website,registrar,principal,contact_no,fax,status,autonomy,minority])
csv_file.close()
#visualizing the data
data = pd.read_csv('college_details.csv')
#bar graph that shows region wise count of engineering colleges-rural or urban
data['Region Type'].value_counts().plot(kind='bar')
#pie chart showing colleges in every region in the form of percentage
data['Region'].value_counts().plot(kind='pie',autopct='%1.2f%%')
#bar graph showing status of colleges i.e goverment aided,autonomousetc
pd.crosstab(data['Region'],data['Status']).plot(kind = 'bar',figsize=(20,10))
pd.crosstab(data['Region'],data['Status'])
#bar graph showing no of colleges that are autonomous or not
pd.crosstab(data['Region'],data['Autonomy Status']).plot(kind = 'pie',figsize=(20,10), subplots="True")
pd.crosstab(data['Region'],data['Autonomy Status'])
# horizontal bar graph showing no of colleges which have minority status
data['Minority status'].value_counts().plot(kind='barh')